In [63]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [64]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'data/train.csv.zip' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

# Data cleaning and normalisation

In [65]:
# we know that very low values are used to signal unavailable data
tX[tX < -900] = np.nan

In [66]:
# split feature 22 by value as planned
tX = np.hstack((np.delete(tX, 22,axis=1), np.stack([tX[:,22] == 0, tX[:,22] == 1, tX[:,22] == 2, tX[:,22] == 3]).T))
print(np.shape(tX))

(250000, 33)


In [67]:
from proj1_helpers import sample_data, standardize
seed = 1

tX_mean = np.nanmean(tX,axis=0)

tX_std = np.nanstd(tX,axis=0)
norm_tX = np.subtract(tX, tX_mean, where=np.isfinite(tX_mean))
norm_tX = np.divide(norm_tX, tX_std, where=tX_std>0)
norm_tX[np.isnan(norm_tX)] =0



norm_tX = np.c_[np.ones((y.shape[0], 1)), norm_tX]
initial_w = np.zeros((norm_tX.shape[1], 1))


#print(initial_w)

print(y)

y[y==-1] = 0
        
print(y)



[ 1. -1. -1. ...  1. -1. -1.]
[1. 0. 0. ... 1. 0. 0.]


In [48]:
from Implementation import sigmoid

sigmoid(0)

0.5

# Logistic Regression


In [68]:
from Implementation import logistic_regression_gd

# init parameters
max_iter = 4000
gamma = 0.00001
initial_w = np.zeros((norm_tX.shape[1], 1))

print(np.shape(y))
print(np.shape(norm_tX))
print(np.shape(initial_w))
print(y)


    
weights = logistic_regression_gd(y, norm_tX, initial_w, max_iter, gamma)

print(weights)






(250000,)
(250000, 34)
(34, 1)
[1. 0. 0. ... 1. 0. 0.]
Current iteration=0, loss=173286.79513997794, gamma=1e-05
Current iteration=100, loss=173272.9512896622, gamma=1e-05
Current iteration=200, loss=173259.22002903727, gamma=1e-05
Current iteration=300, loss=173245.60055404122, gamma=1e-05
Current iteration=400, loss=173232.09206760937, gamma=1e-05
Current iteration=500, loss=173218.69377961237, gamma=1e-05
Current iteration=600, loss=173205.40490678584, gamma=1e-05
Current iteration=700, loss=173192.2246726617, gamma=1e-05
Current iteration=800, loss=173179.15230749932, gamma=1e-05
Current iteration=900, loss=173166.1870482183, gamma=1e-05
Current iteration=1000, loss=173153.32813833142, gamma=1e-05
Current iteration=1100, loss=173140.5748278781, gamma=1e-05
Current iteration=1200, loss=173127.9263733594, gamma=1e-05
Current iteration=1300, loss=173115.38203767297, gamma=1e-05
Current iteration=1400, loss=173102.9410900489, gamma=1e-05
Current iteration=1500, loss=173090.60280598645,

# Regularized logistic regression


In [44]:
from Implementation import regu_logistic_regression_gd

# init parameters
max_iter = 1600
gamma = 0.00005
#gamma = 0.00000009
lambda_ = 0.1


initial_w = np.zeros((norm_tX.shape[1], 1))


weights = regu_logistic_regression_gd(y, norm_tX, lambda_, initial_w, max_iter, gamma )
print(weights)

Current iteration=0, loss=173286.79514050332
Current iteration=100, loss=454796.8530979841
Current iteration=200, loss=471127.5292027239


KeyboardInterrupt: 

# Least squares and Polynomial regression


In [170]:
#weights = polynomial_regression(norm_tX)
#weights = polynomial_regression(norm_tX2)

# Split data



In [190]:
def split_data(x, y, ratio, seed=1):
    """split the dataset based on the split ratio."""
    # set seed
    np.random.seed(seed)
    # generate random indices
    num_row = len(y)
    indices = np.random.permutation(num_row)
    index_split = int(np.floor(ratio * num_row))
    index_tr = indices[: index_split]
    index_te = indices[index_split:]
    # create split
    x_tr = x[index_tr]
    x_te = x[index_te]
    y_tr = y[index_tr]
    y_te = y[index_te]
    return x_tr, x_te, y_tr, y_te

In [191]:
from Implementation import compute_mse, calculate_loss

def train_test_split_demo(x, y, ratio, seed):
    """polynomial regression with different split ratios and different degrees."""
    x_tr, x_te, y_tr, y_te = split_data(x, y, ratio, seed)
    # form tx
    #tx_tr = build_poly(x_tr, degree)
    #tx_te = build_poly(x_te, degree)
   
    tx_tr =x_tr
    tx_te = x_te
    #tx_tr = np.ones((len(x_tr), 1))
    #tx_tr = np.c_[tx_tr, np.power(x_tr, 1)]
    #tx_te = np.ones((len(x_te), 1))
    #tx_te = np.c_[tx_te, np.power(x_te, 1)]
    

    # init parameters
    max_iter = 1000
    gamma = 0.00000009
    initial_w = np.zeros((tx_tr.shape[1], 1))
    
    print(np.shape(y_tr))
    print(np.shape(tx_tr))
    print(np.shape(initial_w))
    


    weight = logistic_regression_gd(y_tr, tx_tr, initial_w, max_iter, gamma)
    
    y_tr = np.expand_dims(y_tr, axis=1)
    y_te = np.expand_dims(y_te, axis=1)
    
    # calculate RMSE for train and test data.
    #rmse_tr = np.sqrt(2 * compute_mse(y_tr, tx_tr, weight))
    #rmse_te = np.sqrt(2 * compute_mse(y_te, tx_te, weight))
    
    #calculate cost for train and test data
    cost_tr = calculate_loss(y_tr, tx_tr, weight)
    cost_te = calculate_loss(y_te, tx_te, weight)

    print("proportion={p}, logistic reg, Training loss={tr:.3f}, Testing loss={te:.3f}".format(
          p=ratio, tr=cost_tr, te=cost_te))
    return weight

In [195]:
seed = 6
degrees = [7]
split_ratio = 0.7
#split_ratios = [0.7, 0.8 , 0.9]
weights = train_test_split_demo(norm_tX, y, split_ratio, seed)


#for split_ratio in split_ratios:
#      weights = train_test_split_demo(norm_tX, y, split_ratio, seed)
        


(175000,)
(175000, 34)
(34, 1)
Current iteration=0, loss=121300.75659798345, gamma=9e-08
Current iteration=100, loss=16567.575101411116, gamma=1e-09
Current iteration=200, loss=14463.579866057495, gamma=1e-09
Current iteration=300, loss=12379.821750837247, gamma=1e-09
Current iteration=400, loss=10315.788958539182, gamma=1e-09
Current iteration=500, loss=8270.987557714107, gamma=1e-09
Current iteration=600, loss=6608.270007891391, gamma=5e-10
Current iteration=700, loss=5600.506474584108, gamma=5e-10
Current iteration=800, loss=4597.279974828474, gamma=5e-10
Current iteration=900, loss=3598.535037165144, gamma=5e-10
loss=2604.217129898301
proportion=0.7, logistic reg, Training loss=2604.217, Testing loss=1366.612
(200000,)
(200000, 34)
(34, 1)
Current iteration=0, loss=138629.43611198076, gamma=9e-08
Current iteration=100, loss=13434.861866862237, gamma=1e-09
Current iteration=200, loss=10760.04721236047, gamma=1e-09
Current iteration=300, loss=8113.413455710848, gamma=1e-09
Current it

## Generate predictions and save ouput in csv format for submission:

In [69]:
DATA_TEST_PATH = 'data/test.csv.zip' # TODO: download train data and supply path here 
y, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [70]:
# we know that very low values are used to signal unavailable data
tX_test[tX_test < -900] = np.nan

In [71]:
# split feature 22 by value as planned
tX_test = np.hstack((np.delete(tX_test, 22,axis=1), np.stack([tX_test[:,22] == 0, tX_test[:,22] == 1, tX_test[:,22] == 2, tX_test[:,22] == 3]).T))
#print(np.shape(tX_test))

In [72]:
#tX_test_mean = np.nanmean(tX_test,axis=0)
#tX_test_std = np.nanstd(tX_test,axis=0)
#norm_tX_test = np.subtract(tX_test, tX_test_mean, where=np.isfinite(tX_test_mean))
#norm_tX_test = np.divide(norm_tX_test, tX_test_std, where=tX_test_std>0)


norm_tX_test = np.subtract(tX_test, tX_mean, where=np.isfinite(tX_mean))
norm_tX_test = np.divide(norm_tX_test, tX_std, where=tX_std>0)
norm_tX_test[np.isnan(norm_tX_test)] =0
norm_tX_test = np.c_[np.ones((y.shape[0], 1)), norm_tX_test]


#norm_tX_test = build_poly(norm_tX_test, 7)


In [73]:
OUTPUT_PATH = 'data/sample-submission' # TODO: fill in desired name of output file for submission
#print(np.shape(y))
#print(np.shape(norm_tX_test))
#print(np.shape(weights))
print(weights)
y_pred = predict_labels(weights, norm_tX_test)

create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

[[ 1.34362703e-02]
 [ 1.85672892e-04]
 [-6.38878717e-03]
 [-2.42917686e-04]
 [ 3.29591051e-03]
 [ 1.85172324e-03]
 [ 1.76455399e-03]
 [-1.65259864e-03]
 [ 4.08605078e-04]
 [-3.83420675e-04]
 [ 2.56376334e-03]
 [-3.55705788e-03]
 [ 4.83848215e-03]
 [ 1.73910041e-03]
 [ 4.20129133e-03]
 [-1.95572528e-05]
 [-8.29492100e-05]
 [-6.12787579e-04]
 [ 2.32570677e-05]
 [ 7.63452575e-05]
 [ 2.66634196e-04]
 [ 1.33690599e-04]
 [ 2.23752897e-03]
 [ 1.11447575e-03]
 [ 3.19649933e-06]
 [-2.12047832e-06]
 [-1.76170250e-04]
 [ 7.28439772e-06]
 [-3.46256595e-05]
 [ 2.20377592e-03]
 [-2.56361289e-03]
 [ 3.55284733e-04]
 [ 3.14678671e-03]
 [-6.01219900e-04]]
[[-0.01387732]
 [ 0.00076037]
 [-0.0026117 ]
 ...
 [ 0.01115793]
 [ 0.02375724]
 [-0.01264391]]
